### Site info:
title: jneeee
tagline: Jn's note
author: jneeee
email: jneeee@qq.com
description: "" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Jn's note"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://jneeee.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
github_username: jneeee
favicon: "/img/favicon.ico"

### Site setting:
permalink: /:year-:month-:day-:title:output_ext
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "one" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
      Home: "首页"
      About: "关于"
      Guestbook: "留言"
      Subscribe: "订阅"

### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: BRAVE NEW WORLD
        href: http://junphy.com/
        title: BRAVE NEW WORLD
      - name: xmoiduts
        href: https://xmoiduts.github.io
        title: xmoiduts

### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
